import type { TranslationMap } from "../lib/types.ts";

export const ar: TranslationMap = {
  common: { health: "الصحة", ok: "موافق", online: "متصل", offline: "غير متصل", connect: "اتصال", refresh: "تحديث", enabled: "مفعل", disabled: "معطل", na: "غ/م", version: "الإصدار", docs: "المستندات", theme: "السمة", resources: "الموارد", search: "بحث", send: "إرسال", delete: "حذف", status: "الحالة", none: "لا شيء", actions: "الإجراءات", models: "النماذج", events: "الأحداث", general: "عام", url: "الرابط" },
  nav: { chat: "محادثة", control: "التحكم", agent: "الوكيل", settings: "الإعدادات", expand: "توسيع الشريط الجانبي", collapse: "طي الشريط الجانبي", navigate: "تنقل" },
  tabs: { overview: "نظرة عامة", channels: "القنوات", sessions: "الجلسات", usage: "الاستخدام والمقاييس", cron: "المهام المجدولة", skills: "المهارات", chat: "محادثة", config: "الإعدادات", aiAgents: "وكلاء الذكاء الاصطناعي", debug: "تصحيح", logs: "السجلات", peers: "الأجهزة" },
  subtitles: { overview: "الحالة ونقاط الدخول والصحة.", channels: "القنوات والإعدادات.", sessions: "الجلسات النشطة والافتراضية.", usage: "استخدام API والتكاليف.", cron: "الإيقاظات والتشغيل المتكرر.", skills: "المهارات ومفاتيح API.", chat: "محادثة البوابة للتدخل السريع.", config: "تحرير coreblow.json.", aiAgents: "الوكلاء والنماذج والمهارات والأدوات والذاكرة والجلسة.", debug: "اللقطات والأحداث وRPC.", logs: "سجلات البوابة المباشرة." },
  overview: { access: { title: "الوصول إلى البوابة", subtitle: "أين تتصل لوحة التحكم وكيف تتم المصادقة.", wsUrl: "رابط WebSocket", token: "رمز البوابة", password: "كلمة المرور", language: "اللغة", connectHint: "انقر اتصال لتطبيق تغييرات الاتصال." }, health: { title: "صحة النظام", checkHealth: "فحص صحة النظام", started: "تم بدء النظام", pollFailed: "فشل فحص الصحة" }, status: { connected: "متصل", connectedServer: "متصل بخادم البوابة", disconnected: "غير متصل", notConnected: "غير متصل", reconnect: "إعادة اتصال البوابة", reconnectWs: "إعادة الاتصال بـ WebSocket", coreblowOnline: "CoreBlow متصل" }, palette: { placeholder: "اكتب أمرا...", noResults: "لم يتم العثور على أوامر", navigateHint: "↑↓ تنقل", selectHint: "↵ تحديد", closeHint: "esc إغلاق", toggleHint: "⌘K للتبديل" } },
  chat: { activeChat: "محادثة نشطة", newSession: "جلسة محادثة جديدة", createSession: "إنشاء جلسة محادثة جديدة", resetMessages: "إعادة تعيين الرسائل", openInChat: "فتح في المحادثة", selectModel: "نموذج المحادثة", defaultModel: "النموذج الافتراضي", loadingModels: "جار تحميل النماذج...", arguments: "الوسائط", newShort: "جديد", empty: "أرسل رسالة إلى CoreBlow", waiting: "بانتظار الرد...", messagePlaceholder: "رسالة إلى CoreBlow...", stop: "إيقاف", connectToChat: "قم بتكوين رابط البوابة أدناه للاتصال", connectFailed: "فشل الاتصال" },
  sessions: { title: "الجلسات", active: "الجلسات النشطة", list: "قائمة الجلسات النشطة", maxConcurrent: "الحد الأقصى للجلسات المتزامنة", fetchFailed: "فشل جلب الجلسات", managedByAgentEngine: "{count} جلسات يديرها AgentEngine", newSession: "جلسة جديدة", searchPlaceholder: "ابحث في الجلسات...", deleteSelected: "حذف {count} المحددة", loading: "جار تحميل الجلسات...", emptyTitle: "لم يتم العثور على جلسات", emptySubtitle: "ابدأ محادثة لإنشاء جلستك الأولى", columnSession: "الجلسة", columnModel: "النموذج", columnTurns: "الأدوار", columnTokens: "الرموز", columnUpdated: "آخر تحديث", justNow: "الآن", minutesAgo: "قبل {count} د", hoursAgo: "قبل {count} س", confirmDelete: "تأكيد؟" },
  agents: { title: "وكلاء الذكاء الاصطناعي", agentLabel: "وكيل", model: "النموذج", state: "الحالة", turns: "الأدوار", tokens: "الرموز", activeSummary: "{count} وكلاء نشطون", newAgent: "وكيل جديد", createAgent: "إنشاء وكيل", modelPlaceholder: "النموذج (اختياري، مثل claude-sonnet-4-20250514)", systemPromptPlaceholder: "موجه النظام (اختياري)", cancel: "إلغاء", create: "إنشاء", loading: "جار تحميل الوكلاء...", emptyTitle: "لا توجد وكلاء قيد التشغيل", emptySubtitle: "أنشئ وكيلا أو ابدأ جلسة محادثة", toolsAvailable: "{count} أدوات متاحة", defaultProvider: "المزود الافتراضي", defaultModel: "النموذج الافتراضي", contextWindow: "نافذة السياق", maxOutput: "الحد الأقصى لرموز الإخراج", maxTurns: "الحد الأقصى للأدوار لكل تشغيل", sandboxDir: "مجلد Sandbox", fetchFailed: "فشل جلب الوكلاء", registeredTools: "الأدوات المسجلة" },
  skills: { title: "المهارات", ready: "جاهز", needsSetup: "يتطلب إعدادا", readySummary: "{ready} من {total} مهارات جاهزة", searchPlaceholder: "ابحث في المهارات...", loading: "جار تحميل المهارات...", filter: { all: "الكل", ready: "جاهز", disabled: "معطل" }, noMatch: "لا توجد مهارات تطابق الفلتر", noRegistered: "لا توجد مهارات مسجلة" },
  config: { title: "الإعدادات", subtitle: "إعدادات تشغيل AgentEngine", save: "حفظ", updated: "تم تحديث {path}", saveFailed: "فشل: {message}", visual: "مرئي", loading: "جار تحميل الإعدادات...", modelConfiguration: "إعدادات النموذج", engineLimits: "حدود المحرك", toolPolicy: "سياسة الأدوات", autoApprove: "موافقة تلقائية", requireApproval: "يتطلب موافقة", denied: "مرفوض", runtimeStatus: "حالة التشغيل", toolsCount: "{count} أدوات", gatewayConnection: "اتصال البوابة", fetchFailed: "فشل جلب الإعدادات", invalidJson: "معلمات JSON غير صالحة" },
  debug: { title: "وحدة التصحيح", rpc: "استدعاءات RPC", rpcConsole: "وحدة RPC", rpcConsoleSubtitle: "إرسال استدعاءات RPC خام إلى البوابة", methodPlaceholder: "الطريقة (مثال health.snapshot)", response: "الاستجابة", quickRpc: "RPC سريع", rpcHistory: "سجل RPC", callsSummary: "{count} استدعاءات", eventStream: "تدفق الأحداث", filterEventsPlaceholder: "تصفية الأحداث...", noEvents: "لا توجد أحداث", connection: "الاتصال", rpcHealth: "health.snapshot", rpcSessions: "sessions.list", rpcModels: "models.list" },
  logs: { title: "السجلات", entriesSummary: "{shown} من {total} إدخالات", export: "تصدير", clear: "مسح", filterPlaceholder: "تصفية السجلات...", autoFollow: "متابعة تلقائية", empty: "لا توجد إدخالات سجل", emptyFiltered: "لا توجد إدخالات سجل تطابق الفلتر" },
  usage: { title: "الاستخدام والمقاييس", subtitle: "استهلاك الرموز وتقديرات التكلفة", totalTokens: "إجمالي الرموز", estimatedCost: "التكلفة المقدرة", totalTurns: "إجمالي الأدوار", loading: "جار تحميل بيانات الاستخدام...", byModel: "الاستخدام حسب النموذج", tokensCount: "{count} رموز", sessionsCount: "{count} جلسات", perSession: "تفصيل حسب الجلسة", input: "الإدخال", output: "الإخراج", total: "الإجمالي", cost: "التكلفة", listModels: "قائمة النماذج المتاحة" },
  cron: { title: "المهام المجدولة", runNow: "تشغيل الآن", scheduledSummary: "{count} مهام مجدولة", loading: "جار تحميل مهام cron...", emptyTitle: "لا توجد مهام cron مكونة", emptySubtitle: "يتم تعريف مهام cron في إعدادات البوابة", name: "الاسم", schedule: "الجدول", runs: "التشغيلات", lastRun: "آخر تشغيل" },
  languages: { en: "English", ar: "العربية", de: "Deutsch", es: "Español", fr: "Français", id: "Bahasa Indonesia", ja: "日本語", ko: "한국어", pt: "Português", zh: "中文" },
  errors: { unknown: "حدث خطأ غير معروف" },
};
