import type { TranslationMap } from "../lib/types.ts";

export const ja: TranslationMap = {
  common: { health: "ヘルス", ok: "OK", online: "オンライン", offline: "オフライン", connect: "接続", refresh: "更新", enabled: "有効", disabled: "無効", na: "該当なし", version: "バージョン", docs: "ドキュメント", theme: "テーマ", resources: "リソース", search: "検索", send: "送信", delete: "削除", status: "ステータス", none: "なし", actions: "アクション", models: "モデル", events: "イベント", general: "一般", url: "URL" },
  nav: { chat: "チャット", control: "コントロール", agent: "エージェント", settings: "設定", expand: "サイドバーを展開", collapse: "サイドバーを折りたたむ", navigate: "ナビゲーション" },
  tabs: { overview: "概要", channels: "チャンネル", sessions: "セッション", usage: "使用状況とメトリクス", cron: "スケジュールタスク", skills: "スキル", chat: "チャット", config: "設定", aiAgents: "AIエージェント", debug: "デバッグ", logs: "ログ", peers: "デバイス" },
  subtitles: { overview: "ステータス、エントリポイント、ヘルス。", channels: "チャンネルと設定。", sessions: "アクティブなセッションとデフォルト。", usage: "API使用量とコスト。", cron: "ウェイクアップと定期実行。", skills: "スキルとAPIキー。", chat: "クイック介入用ゲートウェイチャット。", config: "coreblow.jsonを編集。", aiAgents: "エージェント、モデル、スキル、ツール、メモリ、セッション。", debug: "スナップショット、イベント、RPC。", logs: "ライブゲートウェイログ。" },
  overview: { access: { title: "ゲートウェイアクセス", subtitle: "ダッシュボードの接続先と認証方法。", wsUrl: "WebSocket URL", token: "ゲートウェイトークン", password: "パスワード", language: "言語", connectHint: "接続をクリックして接続変更を適用します。" }, health: { title: "システムヘルス", checkHealth: "システムヘルスを確認", started: "システム開始", pollFailed: "ヘルスチェック失敗" }, status: { connected: "接続済み", connectedServer: "ゲートウェイサーバーに接続済み", disconnected: "切断済み", notConnected: "未接続", reconnect: "ゲートウェイに再接続", reconnectWs: "WebSocketに再接続", coreblowOnline: "CoreBlow オンライン" }, palette: { placeholder: "コマンドを入力...", noResults: "コマンドが見つかりません", navigateHint: "↑↓ 移動", selectHint: "↵ 選択", closeHint: "esc 閉じる", toggleHint: "⌘K で切り替え" } },
  chat: { activeChat: "アクティブチャット", newSession: "新規チャットセッション", createSession: "新しいチャットセッションを作成", resetMessages: "メッセージをリセット", openInChat: "チャットで開く", selectModel: "チャットモデル", defaultModel: "デフォルトモデル", loadingModels: "モデルを読み込み中...", arguments: "引数", newShort: "新規", empty: "CoreBlowにメッセージを送信", waiting: "応答を待機中...", messagePlaceholder: "CoreBlowへメッセージ...", stop: "停止", connectToChat: "接続するには以下にゲートウェイURLを設定してください", connectFailed: "接続失敗" },
  sessions: { title: "セッション", active: "アクティブセッション", list: "アクティブセッション一覧", maxConcurrent: "最大同時セッション数", fetchFailed: "セッションの取得に失敗", managedByAgentEngine: "AgentEngineが管理するセッション: {count}", newSession: "新規セッション", searchPlaceholder: "セッションを検索...", deleteSelected: "選択した{count}件を削除", loading: "セッションを読み込み中...", emptyTitle: "セッションが見つかりません", emptySubtitle: "チャットを開始して最初のセッションを作成します", columnSession: "セッション", columnModel: "モデル", columnTurns: "ターン", columnTokens: "トークン", columnUpdated: "更新日時", justNow: "たった今", minutesAgo: "{count}分前", hoursAgo: "{count}時間前", confirmDelete: "確認しますか？" },
  agents: { title: "AIエージェント", agentLabel: "エージェント", model: "モデル", state: "状態", turns: "ターン", tokens: "トークン", activeSummary: "アクティブなエージェント: {count}", newAgent: "新規エージェント", createAgent: "エージェントを作成", modelPlaceholder: "モデル（任意、例: claude-sonnet-4-20250514）", systemPromptPlaceholder: "システムプロンプト（任意）", cancel: "キャンセル", create: "作成", loading: "エージェントを読み込み中...", emptyTitle: "実行中のエージェントはありません", emptySubtitle: "エージェントを作成するかチャットセッションを開始します", toolsAvailable: "利用可能なツール: {count}", defaultProvider: "デフォルトプロバイダー", defaultModel: "デフォルトモデル", contextWindow: "コンテキストウィンドウ", maxOutput: "最大出力トークン", maxTurns: "実行あたり最大ターン", sandboxDir: "サンドボックスディレクトリ", fetchFailed: "エージェントの取得に失敗", registeredTools: "登録済みツール" },
  skills: { title: "スキル", ready: "準備完了", needsSetup: "設定が必要", readySummary: "{total}件中{ready}件のスキルが準備完了", searchPlaceholder: "スキルを検索...", loading: "スキルを読み込み中...", filter: { all: "すべて", ready: "準備完了", disabled: "無効" }, noMatch: "フィルターに一致するスキルがありません", noRegistered: "登録済みスキルがありません" },
  config: { title: "設定", subtitle: "AgentEngineランタイム設定", save: "保存", updated: "{path}を更新しました", saveFailed: "失敗: {message}", visual: "ビジュアル", loading: "設定を読み込み中...", modelConfiguration: "モデル設定", engineLimits: "エンジン制限", toolPolicy: "ツールポリシー", autoApprove: "自動承認", requireApproval: "承認が必要", denied: "拒否", runtimeStatus: "ランタイム状態", toolsCount: "{count}個のツール", gatewayConnection: "ゲートウェイ接続", fetchFailed: "設定の取得に失敗", invalidJson: "無効なJSONパラメーター" },
  debug: { title: "デバッグコンソール", rpc: "RPC呼び出し", rpcConsole: "RPCコンソール", rpcConsoleSubtitle: "ゲートウェイへ生のRPC呼び出しを送信します", methodPlaceholder: "メソッド（例: health.snapshot）", response: "レスポンス", quickRpc: "クイックRPC", rpcHistory: "RPC履歴", callsSummary: "{count}件の呼び出し", eventStream: "イベントストリーム", filterEventsPlaceholder: "イベントをフィルター...", noEvents: "イベントはありません", connection: "接続", rpcHealth: "health.snapshot", rpcSessions: "sessions.list", rpcModels: "models.list" },
  logs: { title: "ログ", entriesSummary: "{total}件中{shown}件", export: "エクスポート", clear: "クリア", filterPlaceholder: "ログをフィルター...", autoFollow: "自動追従", empty: "ログエントリはありません", emptyFiltered: "フィルターに一致するログはありません" },
  usage: { title: "使用状況とメトリクス", subtitle: "トークン消費量とコスト見積もり", totalTokens: "合計トークン", estimatedCost: "推定コスト", totalTurns: "合計ターン", loading: "使用状況データを読み込み中...", byModel: "モデル別使用状況", tokensCount: "{count}トークン", sessionsCount: "{count}セッション", perSession: "セッション別内訳", input: "入力", output: "出力", total: "合計", cost: "コスト", listModels: "利用可能なモデル一覧" },
  cron: { title: "スケジュールタスク", runNow: "今すぐ実行", scheduledSummary: "スケジュール済みジョブ: {count}", loading: "Cronジョブを読み込み中...", emptyTitle: "Cronジョブが設定されていません", emptySubtitle: "Cronジョブはゲートウェイ設定で定義されます", name: "名前", schedule: "スケジュール", runs: "実行回数", lastRun: "最終実行" },
  languages: { en: "English", ar: "العربية", de: "Deutsch", es: "Español", fr: "Français", id: "Bahasa Indonesia", ja: "日本語", ko: "한국어", pt: "Português", zh: "中文" },
  errors: { unknown: "不明なエラーが発生しました" },
};
