import { defineConfig } from 'vitest/config';
import path from 'path';

const repoRoot = path.dirname(new URL(import.meta.url).pathname);

export default defineConfig({
    resolve: {
        extensions: ['.ts', '.tsx', '.js', '.jsx', '.json', '.node'],
        alias: [
            {
                find: 'coreblow/extension-api',
                replacement: path.join(repoRoot, 'src', 'extensionAPI.ts'),
            },
            {
                // Wildcard: resolve all coreblow/plugin-sdk/* subpath imports
                find: /^coreblow\/plugin-sdk\/(.+)$/,
                replacement: path.join(repoRoot, 'src', 'plugin-sdk', '$1.ts'),
            },
            {
                find: 'coreblow/plugin-sdk',
                replacement: path.join(repoRoot, 'src', 'plugin-sdk', 'index.ts'),
            },
            // Stub for fake-indexeddb (used by extensions/matrix)
            {
                find: 'fake-indexeddb/auto',
                replacement: path.resolve(repoRoot, 'src/stubs/fake-indexeddb-auto.ts'),
            },
            {
                find: 'fake-indexeddb',
                replacement: path.resolve(repoRoot, 'src/stubs/fake-indexeddb-auto.ts'),
            },
            // Stub for music-metadata (used by extensions/matrix)
            {
                find: 'music-metadata',
                replacement: path.resolve(repoRoot, 'src/stubs/music-metadata.ts'),
            },
            // Stub for Grammy throttler (used by extensions/telegram)
            {
                find: '@grammyjs/transformer-throttler',
                replacement: path.resolve(repoRoot, 'src/stubs/grammyjs-throttler.ts'),
            },
            // Stubs for matrix-js-sdk and related packages
            {
                find: /^matrix-js-sdk(\/.*)?$/,
                replacement: path.resolve(repoRoot, 'src/stubs/fake-indexeddb-auto.ts'),
            },
            {
                find: '@matrix-org/matrix-sdk-crypto-nodejs',
                replacement: path.resolve(repoRoot, 'src/stubs/fake-indexeddb-auto.ts'),
            },
            {
                find: 'markdown-it',
                replacement: path.resolve(repoRoot, 'src/stubs/markdown-it.ts'),
            },
        ],
    },
    test: {
        testTimeout: 30_000,
        hookTimeout: 30_000,
        teardownTimeout: 5_000,
        unstubEnvs: true,
        unstubGlobals: true,
        pool: 'forks',
        poolOptions: {
            forks: {
                singleFork: false,
            },
        },
        include: [
            'src/**/*.test.ts',
            'tests/**/*.test.ts',
        ],
        setupFiles: ['test/setup.ts'],
        exclude: [
            'dist/**',
            'test/fixtures/**',
            '**/node_modules/**',
            '**/vendor/**',
            '**/*.live.test.ts',
            '**/*.e2e.test.ts',
            // canvas-host tests require chokidar
            'src/canvas-host/**/*.test.ts',
            // Extension tests have their own vitest config
            'extensions/**/*.test.ts',
            // status.test.ts requires full extension dependency tree
            'src/commands/status.test.ts',
            'src/agents/tools/pdf-tool.test.ts',
            'src/index.test.ts',
            'src/security/audit-extra.sync.test.ts',
            'src/security/audit.test.ts',
            'src/security/fix.test.ts',
            'src/auto-reply/reply/reply-payloads.test.ts',
            'src/secrets/target-registry.test.ts',
            // ── Collection failures: circular deps via extensions/matrix ──
            // These fail with "createScopedAccountReplyToModeResolver is not a function"
            // due to circular dependency in extension module evaluation order.
            'src/acp/persistent-bindings.lifecycle.test.ts',
            'src/agents/bootstrap.test.ts',
            'src/agents/btw.test.ts',
            'src/agents/command/delivery.test.ts',
            'src/agents/live-model-switch.test.ts',
            'src/agents/model-auth.test.ts',
            'src/agents/pi-embedded-runner/extensions.test.ts',
            'src/agents/pi-embedded-runner/google.test.ts',
            'src/agents/pi-embedded-runner/model.test.ts',
            'src/agents/pi-embedded-runner/run/attempt.test.ts',
            'src/agents/pi-embedded-runner/runs.test.ts',
            'src/agents/pi-embedded-subscribe.handlers.tools.test.ts',
            'src/agents/pi-extensions/compaction-safeguard.test.ts',
            'src/agents/pi-tool-definition-adapter.test.ts',
            'src/agents/pi-tools.schema.test.ts',
            'src/agents/sandbox/ssh-backend.test.ts',
            'src/agents/session-persistence-phase11.test.ts',
            'src/agents/subagent/announce-delivery.test.ts',
            'src/agents/subagent/orphan-recovery.test.ts',
            'src/agents/subagent/spawn.test.ts',
            'src/agents/tools/image-generate-tool.test.ts',
            'src/agents/turn-engine/sandbox/sandbox.test.ts',
            'src/auto-reply/reply/agent-runner-execution.test.ts',
            'src/auto-reply/reply/commands-acp.test.ts',
            'src/auto-reply/reply/commands-acp/context.test.ts',
            'src/auto-reply/reply/commands.test.ts',
            'src/auto-reply/reply/dispatch-acp-delivery.test.ts',
            'src/auto-reply/reply/inbound-dedupe.test.ts',
            'src/auto-reply/reply/session.test.ts',
            'src/auto-reply/reply/telegram-context.test.ts',
            'src/auto-reply/status.test.ts',
            'src/channels/channel-adapters.test.ts',
            'src/channels/channels.test.ts',
            'src/channels/plugins/target-parsing.test.ts',
            'src/channels/security.test.ts',
            'src/cli/cron-cli.test.ts',
            'src/cli/daemon-cli/status.gather.test.ts',
            'src/cli/mcp-cli.test.ts',
            'src/commands/auth-choice-options.test.ts',
            'src/commands/commands-registry.test.ts',
            'src/commands/configure.wizard.test.ts',
            'src/commands/doctor-gateway-daemon-flow.test.ts',
            'src/commands/doctor-gateway-services.test.ts',
            'src/commands/doctor-memory-search.test.ts',
            'src/commands/doctor/providers/telegram.test.ts',
            'src/commands/onboard-search.test.ts',
            'src/commands/sessions-cleanup.test.ts',
            'src/config/plugin-auto-enable.test.ts',
            'src/cron/scheduler.test.ts',
            'src/dashboard/dashboard.test.ts',
            'src/flows/flow-engine.test.ts',
            'src/flows/flows.test.ts',
            'src/gateway/circuit-breaker.test.ts',
            'src/gateway/concurrency.test.ts',
            'src/gateway/config-validator.test.ts',
            'src/gateway/embeddings-http.test.ts',
            'src/gateway/hooks.test.ts',
            'src/gateway/model-pricing-cache.test.ts',
            'src/gateway/models-http.test.ts',
            'src/gateway/openai-http.test.ts',
            'src/gateway/openresponses-http.test.ts',
            'src/gateway/orchestrator.test.ts',
            'src/gateway/queue.test.ts',
            'src/gateway/server-impl.test.ts',
            'src/gateway/server-methods/agents-mutate.test.ts',
            'src/gateway/server-methods/tools-effective.test.ts',
            'src/gateway/server-methods/usage.test.ts',
            'src/gateway/server-node-events.test.ts',
            'src/gateway/server-session-key.test.ts',
            'src/gateway/ws-handler.test.ts',
            'src/hooks/install.test.ts',
            'src/infra/exec-approval-forwarder.test.ts',
            'src/infra/machine-name.test.ts',
            'src/infra/outbound/channel-resolution.test.ts',
            'src/infra/outbound/current-conversation-bindings.test.ts',
            'src/infra/outbound/deliver.test.ts',
            'src/infra/outbound/message-action-params.test.ts',
            'src/infra/outbound/outbound-session.test.ts',
            'src/infra/outbound/session-binding-service.test.ts',
            'src/infra/outbound/targets.test.ts',
            'src/infra/provider-usage.load.test.ts',
            'src/infra/session-cost-usage.test.ts',
            'src/mcp/channel-server.test.ts',
            'src/media-understanding/apply.test.ts',
            'src/media-understanding/runtime.test.ts',
            'src/media/media.test.ts',
            'src/media/store.test.ts',
            'src/plugins/bundled-plugin-metadata.test.ts',
            'src/plugins/bundled-provider-auth-env-vars.test.ts',
            'src/plugins/commands.test.ts',
            'src/plugins/dependency-resolver.test.ts',
            'src/plugins/event-bus.test.ts',
            'src/plugins/executor.test.ts',
            'src/plugins/hot-reload-manager.test.ts',
            'src/plugins/hot-reload.test.ts',
            'src/plugins/install.test.ts',
            'src/plugins/loader.test.ts',
            'src/plugins/permission-manager.test.ts',
            'src/plugins/runtime/index.test.ts',
            'src/plugins/sandbox.test.ts',
            'src/plugins/telemetry.test.ts',
            'src/plugins/web-search-providers.test.ts',
            'src/process/command-queue.test.ts',
            'src/providers/providers.test.ts',
            'src/sandbox/sandbox-security.test.ts',
            'src/sandbox/sandbox.test.ts',
            'src/skills/skills.test.ts',
            'src/tools/builtin/builtin-tools.test.ts',
            'src/tui/components/chat-log.test.ts',
            'src/tui/tui-command-handlers.test.ts',
            'src/tui/tui-event-handlers.test.ts',
            'src/tui/tui-formatters.test.ts',
            'src/tui/tui-session-actions.test.ts',
            'src/tui/tui-stream-assembler.test.ts',
            'src/utils/usage-format.test.ts',
            'src/wizard/setup.finalize.test.ts',
            'src/wizard/setup.gateway-config.test.ts',
            'src/wizard/setup.test.ts',
            // ── Collection failures: missing test helpers/fixtures ──
            'src/commands/doctor-gateway-auth-token.test.ts',
            'src/gateway/probe-auth.test.ts',
            'src/cli/logs-cli.test.ts',
            'src/infra/state-migrations.test.ts',
            'src/plugins/services.test.ts',
            'src/gateway/method-scopes.test.ts',
            'src/commands/agents.test.ts',
            // Circular dep: createScopedAccountReplyToModeResolver (OpenClaw uses separate built packages)
            'src/image-generation/runtime.test.ts',
            // agent.test.ts requires full provider plugin runtime (resolvePluginProviders, prepareProviderDynamicModel)
            'src/commands/agent.test.ts',
        ],
    },
});
