export type InstallRecordBase = {
  source: "npm" | "archive" | "path" | "corehub";
  spec?: string;
  sourcePath?: string;
  installPath?: string;
  version?: string;
  resolvedName?: string;
  resolvedVersion?: string;
  resolvedSpec?: string;
  integrity?: string;
  shasum?: string;
  resolvedAt?: string;
  installedAt?: string;
  corehubUrl?: string;
  corehubPackage?: string;
  corehubFamily?: "code-plugin" | "bundle-plugin";
  corehubChannel?: "official" | "community" | "private";
  artifactSha256?: string;
  artifactSize?: number;
  artifactManifestVerified?: boolean;
  artifactManifestSha256?: string;
  artifactStorageKey?: string;
  publisherHandle?: string;
  verifiedAt?: string;
};
