export const browserCoreExamples = [
  "coreblow browser status",
  "coreblow browser start",
  "coreblow browser stop",
  "coreblow browser tabs",
  "coreblow browser open https://example.com",
  "coreblow browser focus abcd1234",
  "coreblow browser close abcd1234",
  "coreblow browser screenshot",
  "coreblow browser screenshot --full-page",
  "coreblow browser screenshot --ref 12",
  "coreblow browser snapshot",
  "coreblow browser snapshot --format aria --limit 200",
  "coreblow browser snapshot --efficient",
  "coreblow browser snapshot --labels",
];

export const browserActionExamples = [
  "coreblow browser navigate https://example.com",
  "coreblow browser resize 1280 720",
  "coreblow browser click 12 --double",
  'coreblow browser type 23 "hello" --submit',
  "coreblow browser press Enter",
  "coreblow browser hover 44",
  "coreblow browser drag 10 11",
  "coreblow browser select 9 OptionA OptionB",
  "coreblow browser upload /tmp/coreblow/uploads/file.pdf",
  'coreblow browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "coreblow browser dialog --accept",
  'coreblow browser wait --text "Done"',
  "coreblow browser evaluate --fn '(el) => el.textContent' --ref 7",
  "coreblow browser console --level error",
  "coreblow browser pdf",
];
