#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*)
        if command -v cygpath > /dev/null 2>&1; then
            basedir=`cygpath -w "$basedir"`
        fi
    ;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/febrinanda/coreblow.com/gateway/dist/node_modules:/Users/febrinanda/coreblow.com/gateway/node_modules:/Users/febrinanda/coreblow.com/node_modules:/Users/febrinanda/node_modules:/Users/node_modules:/node_modules:/Users/febrinanda/coreblow.com/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/febrinanda/coreblow.com/gateway/dist/node_modules:/Users/febrinanda/coreblow.com/gateway/node_modules:/Users/febrinanda/coreblow.com/node_modules:/Users/febrinanda/node_modules:/Users/node_modules:/node_modules:/Users/febrinanda/coreblow.com/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../coreblow/dist/index.js" "$@"
else
  exec node  "$basedir/../coreblow/dist/index.js" "$@"
fi
