/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  DISCORD_DEFAULT_INBOUND_WORKER_TIMEOUT_MS,
  DISCORD_DEFAULT_LISTENER_TIMEOUT_MS,
} from "../../extensions/discord/api.js";
