/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  applyLitellmConfig,
  applyLitellmProviderConfig,
  buildLitellmModelDefinition,
  LITELLM_BASE_URL,
  LITELLM_DEFAULT_MODEL_ID,
  LITELLM_DEFAULT_MODEL_REF,
} from "../../extensions/litellm/api.js";
