/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { resolveSignalAccount } from "../../extensions/signal/api.js";
export type { ResolvedSignalAccount } from "../../extensions/signal/api.js";
