/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { resolveSlackAccount } from "../../extensions/slack/api.js";
export type { ResolvedSlackAccount } from "../../extensions/slack/api.js";
