/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export { parseSlackTarget, resolveSlackChannelId } from "../../extensions/slack/api.js";
