/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  handleSlackAction,
  listSlackDirectoryGroupsLive,
  listSlackDirectoryPeersLive,
  monitorSlackProvider,
  probeSlack,
  resolveSlackChannelAllowlist,
  resolveSlackUserAllowlist,
  sendMessageSlack,
} from "../../extensions/slack/runtime-api.js";
export type { SlackActionContext } from "../../extensions/slack/runtime-api.js";
