/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  isNumericTelegramUserId,
  normalizeTelegramAllowFromEntry,
} from "../../extensions/telegram/api.js";
