/** @internal — Zero consumers. SDK pruning audit 2026-04-24 */
// Generated by scripts/generate-plugin-sdk-facades.mjs. Do not edit manually.
export {
  buildDoubaoCodingProvider,
  buildDoubaoModelDefinition,
  buildDoubaoProvider,
  DOUBAO_BASE_URL,
  DOUBAO_CODING_BASE_URL,
  DOUBAO_CODING_MODEL_CATALOG,
  DOUBAO_MODEL_CATALOG,
} from "../../extensions/volcengine/api.js";
